# Main configuration entry point for MCQA Benchmark
# This file contains the core settings that users will primarily interact with
dataset: /fs/clip-projects/rlab/nbalepur/mcqa-bench/local_datasets/ARC/test.csv

# Metrics to score or refine -> difficulty, shortcuts, writing_flaws, contamination
scoring_metrics: [writing_flaws]
refining_metrics: [writing_flaws]

# Saving directories
cache_dir: cache_logs
dataset_save_dir: refined_dataset
plot_dir: plots
cache_type: overwrite # none | cache | overwrite

skill_run_name: anchor_rewriting_experiments
metric_run_name: ARC_large_scale_fixed
refine_run_name: ARC_large_scale_fixed_rewrite

log_dir: ./atrey_logs