# Main configuration entry point for MCQA Benchmark
# This file contains the core settings that users will primarily interact with
dataset: local_datasets/MMLU/train.csv

# Metrics to score or refine
scoring_metrics: [writing_flaws, shortcuts, contamination, difficulty]
refining_metrics: [writing_flaws, shortcuts, contamination, difficulty]

# Saving directories
cache_dir: cache_logs
dataset_save_dir: refined_dataset
plot_dir: plots
cache_type: cache # none | cache | overwrite

skill_run_name: anchor_large
metric_run_name: large_scale_fixed
refine_run_name: large_scale_fixed