# Skills learning configuration
# This file contains settings for learning model skills from training data

num_samples: 2500


skill_datasets: [/fs/clip-projects/rlab/nbalepur/mcqa-bench/local_datasets/ARC/train.csv,
            /fs/clip-projects/rlab/nbalepur/mcqa-bench/local_datasets/MMLU/train.csv,
            /fs/clip-projects/rlab/nbalepur/mcqa-bench/local_datasets/HellaSwag/train.csv,
            /fs/clip-projects/rlab/nbalepur/mcqa-bench/local_datasets/Super_GPQA/train.csv,
            /fs/clip-projects/rlab/nbalepur/mcqa-bench/local_datasets/truthful_qa/train.csv,
            ]

# For learning skills, we re-use the difficulty metric configuration
difficulty:

  # models: [openai-api/cohere/command-r-08-2024, openai/gpt-5-nano-2025-08-07, google/gemini-2.5-flash-preview-09-2025, anthropic/claude-sonnet-4-5-20250929]

  models: [openai/gpt-5-mini-2025-08-07, openai/gpt-5-nano-2025-08-07, google/gemini-3-flash-preview, together/Qwen/Qwen3-Next-80B-A3B-Instruct]

  # IRT model configuration
  irt_model:
    num_draws: 300
    num_tune: 300
    chains: 5
    cores: 5